# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e1e56243b6e8e0b65a4e765141ce8d4b7269575c6410dcf041cf43982fd4ad430336e97cd0a4a5900936e129a3fd1b9a52e44eccc40ba164738c23cd4670da4

test:
  secret_key_base: 96d90effe874be7f3c797fcd5cd54cb6af97dd528d35f41523158c6841ef8e7647251b487766327a89c1a38fd17b609f95ca90972b1b9215c90496137f51c7b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
